FROM nginx:1.15.8-alpine

copy ./nginx.conf /etc/nginx/nginx.conf
copy ./*.html /usr/share/nginx/html/
#copy ./*.css /usr/share/nginx/html/
#copy ./*.png /usr/share/nginx/html/
#copy ./*.js /usr/share/nginx/html/